### ISSUE TITLE
CasualDark theme

### ISSUE THREAD

**Issue by Accelerando** [IRDeNial/BD-Even-Better-Repo#29]
came as CasualDark.css instead of CasualDark.theme.css

**Comment by IRDeNial** [comment]
The issue with file naming will be fixed in the next update.  (Tonight or tomorrow).

Will let this one come through.

**Comment by IRDeNial** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Files are sometimes not saved properly](https://trello.com/c/wcT2KZIn/1-files-are-sometimes-not-saved-properly)

**Comment by IRDeNial** [comment]
Fixed in pull request #40 and #41
