### ISSUE TITLE
Repo Update - Plugin - Kawaii Emotes

### ISSUE THREAD

**Issue by noodlebox** [IRDeNial/BD-Even-Better-Repo#51]
Plugin Name: `Kawaii Emotes`
Plugin Author: `noodlebox`
Plugin Author GitHub URL: `https://github.com/noodlebox`
Plugin Repo URL: `https://github.com/noodlebox/betterdiscord-plugins`
Plugin Direct URL: `https://raw.githubusercontent.com/noodlebox/betterdiscord-plugins/master/KawaiiEmotes.plugin.js`
Plugin Description: `Better emote parsing for BetterDiscord. Fixes bugs with emotes and tooltips.`

**Comment by noodlebox** [comment]
It doesn't seem that I can apply labels to my issue.

**Comment by IRDeNial** [comment]
It should be mergable.  It's just far easier to remove the possibility of improper formatting & merge conflicts like this since people fork.

Will add later tonight.

**Comment by IRDeNial** [comment]
Addressed in commit 111fb38
