### ISSUE TITLE
EvenBetterDiscord

### ISSUE THREAD

**Issue by DeathStrikeV** [IRDeNial/BD-Even-Better-Repo#58]
Plugin Name: EvenBetterDiscord
Plugin Author: DeathStrikeV
Plugin Author GitHub URL: https://github.com/DeathStrikeV/
Plugin Repo URL: https://github.com/DeathStrikeV/EvenBetterDiscord
Plugin Direct URL: https://raw.githubusercontent.com/DeathStrikeV/EvenBetterDiscord/master/EvenBetterDiscord.plugin.js
Plugin Description: Loads FFZ emotes from alternate repository

**Comment by noodlebox** [comment]
@DeathStrikeV Should use the "raw" URL for your Direct URL:
https://raw.githubusercontent.com/DeathStrikeV/EvenBetterDiscord/master/EvenBetterDiscord.plugin.js

**Comment by DeathStrikeV** [comment]
@noodlebox Whups... Cheers for pointing out that mistake (fixed now), I had a feeling I got the direct URL wrong just now when I checked how my bots upload the same file to discord via bot command... xD

**Comment by IRDeNial** [comment]
Thanks @noodlebox! 👍 
@DeathStrikeV  I'll get to this later tonight.

**Comment by IRDeNial** [comment]
Added in commit 2cfbb68
