### ISSUE TITLE
Quicksave Links to Wrong Plugin

### ISSUE THREAD

**Issue by Nikey646** [IRDeNial/BD-Even-Better-Repo#60]
It links to the Compact Guilds Plugin which isn't listed elsewhere in the repo.

[Offending Lines](https://github.com/IRDeNial/BD-Even-Better-Repo/blob/2cfbb68ff4313bad7333ce7a6e505a2102d7a87c/repo.json#L147-L152)
[Actual Link](https://raw.githubusercontent.com/kosshishub/Quicksave-BD-plugin/master/Quicksave.plugin.js)

**Comment by noodlebox** [comment]
Thanks for pointing that out. It looks like this issue has been in there since the beginning.
