### ISSUE TITLE
Repo Update - Theme - Full Dark

### ISSUE THREAD

**Issue by fluffingtons** [IRDeNial/BD-Even-Better-Repo#65]
Theme Name: `Full Dark`
Theme Author: `fluffy`
Theme Repo URL: `https://github.com/fluffingtons/fulldark`
Theme Direct URL: `https://raw.githubusercontent.com/fluffingtons/fulldark/master/fulldark.theme.css`
Theme Description: `A theme which aims to complete the dark theme for Discord.`

**Comment by IRDeNial** [comment]
Added in commit cb29c71
