### ISSUE TITLE
Repo Update - Plugin - Theme Customizer

### ISSUE THREAD

**Issue by Zerthox** [IRDeNial/BD-Even-Better-Repo#66]
Plugin Name: `Theme Customizer`
Plugin Author: `Zerthox`
Plugin Author GitHub URL: `https://github.com/Zerthox/`
Plugin Repo URL: `https://github.com/Zerthox/BetterDiscord-Plugins/`
Plugin Direct URL: `https://raw.githubusercontent.com/Zerthox/BetterDiscord-Plugins/master/plugins/ThemeCustomizer.plugin.js`
Plugin Description: `Customize CSS variables of themes`

**Comment by IRDeNial** [comment]
Added in commit cb29c71
