### ISSUE TITLE
Repo Update - Plugin - Toggle All

### ISSUE THREAD

**Issue by Zerthox** [IRDeNial/BD-Even-Better-Repo#67]
Plugin Name: `Toggle All`
Plugin Author: `Zerthox`
Plugin Author GitHub URL: `https://github.com/Zerthox/`
Plugin Repo URL: `https://github.com/Zerthox/BetterDiscord-Plugins/`
Plugin Direct URL: `https://raw.githubusercontent.com/Zerthox/BetterDiscord-Plugins/master/plugins/ToggleAll.plugin.js`
Plugin Description: `Enable/disable all plugins or themes with a button`

**Comment by IRDeNial** [comment]
Added in commit cb29c71
