### ISSUE TITLE
Repo Update - Theme - Kobato

### ISSUE THREAD

**Issue by DRedDogPE** [IRDeNial/BD-Even-Better-Repo#68]
Theme Name: Kobato
Theme Author: Syaoran3
Theme Author GitHub URL: https://github.com/DRedDogPE/
Theme Repo URL: https://github.com/DRedDogPE/DiscordThemes/tree/master/Kobato
Theme Direct URL: https://raw.githubusercontent.com/DRedDogPE/DiscordThemes/master/Kobato/Kobato.theme.css
Theme Description: A Kobato theme made for EternalEnd

**Comment by IRDeNial** [comment]
Added to repo.
