### ISSUE TITLE
Repo Update - Theme - Dark Cyan (Flat & Edgy)

### ISSUE THREAD

**Issue by magiruuvelvet** [IRDeNial/BD-Even-Better-Repo#69]
Theme Name: `Dark Cyan (Flat & Edgy)`
Theme Author: `マギルゥーベルベット (magiruuvelvet)`
Theme Author GitHub URL: `https://github.com/magiruuvelvet`
Theme Repo URL: `https://github.com/magiruuvelvet/discord-theme-dark-cyan-flat-edgy/tree/master`
Theme Direct URL: `https://raw.githubusercontent.com/magiruuvelvet/discord-theme-dark-cyan-flat-edgy/master/dark-cyan-flat-edgy.theme.css`
Theme Description: `A dark cyan and flat & edgy theme for Discord`
Preview Screenshot: `https://raw.githubusercontent.com/magiruuvelvet/discord-theme-dark-cyan-flat-edgy/master/screenshots/main-ui.png`

**Comment by IRDeNial** [comment]
Will add this tomorrow morning.

**Comment by magiruuvelvet** [comment]
Thanks.

I made some fixes though as I noticed I forgot to add the `META` line to the CSS. BetterDiscord didn't recognized my theme. This is now fixed.

**Comment by IRDeNial** [comment]
Added
